### ISSUE TITLE
想学习一下

### ISSUE THREAD

**Issue by bonlyge** [EasyTuan/mui-kidApp#4]
用mui开发快一年了，现在也在用，感觉自己写的太low了，就是传参，打开新页面，别的都没考虑，想跟大神持续学习，感谢，

**Comment by EasyTuan** [comment]
我也是学习者，也在一步步的踩坑，如果可以，大家可以一起讨论一起成长

**Comment by bonlyge** [comment]
mui.openWindow({
			url: "search.html",
			id: "index/search.html",
			show: {
				autoShow: true, //页面loaded事件发生后自动显示，默认为true
				aniShow: "none", //页面显示动画，默认为”slide-in-right“；
				event: 'titleUpdate', //页面显示时机，默认为titleUpdate事件时显示
				extras: {} //窗口动画是否使用图片加速
			},
			waiting: {
				autoShow: false, //自动显示等待框，默认为true
			}
		})

在mui打开新页面的时候，我在文档中没有找到show里面的event这个参数，请指教
